In [4]:
import numpy as np

# Definir la matriz
matriz = np.array([[1, 0, -1],
                   [2, 0, 2],
                   [8, 2, -3]])

# Calcular la matriz inversa
matriz_inversa = np.linalg.inv(matriz)

# Imprimir la matriz inversa
print("Matriz original:")
print(matriz)
print("\nMatriz inversa:")
print(matriz_inversa)


Matriz original:
[[ 1  0 -1]
 [ 2  0  2]
 [ 8  2 -3]]

Matriz inversa:
[[ 0.5    0.25   0.   ]
 [-2.75  -0.625  0.5  ]
 [-0.5    0.25  -0.   ]]
